name: Eric Feitel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8858
title: Eric Feitel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9dc6c8'
    - '#d6a999'
    - '#ae5d38'
    - '#026e57'
    - '#59281e'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
